### ISSUE TITLE
编译后不能正常运行

### ISSUE THREAD

**Issue by 7643OvO** [Ho3-L/cs2-paste-ware#1]
编译后不能正常运行，打开没反应

**Comment by Ho3-L** [comment]
请检查dma是否正常

**Comment by 7643OvO** [comment]
可以给个联系方式吗？

**Comment by Ho3-L** [comment]
dc:zEkee#9615

**Comment by Ho3-L** [comment]
这个代码是我最初的一个源，可以说已经放弃了这个项目（我现在投入新项目了,从零开发,并且效果和性能不错），很低的fps（30-60），并且当你处于观察的时候fps会掉到10+，
